### ISSUE TITLE
Set Busy/Unbusy when loading EDS from capabilities file.

### ISSUE THREAD

**Issue by Sarci1** [NIVeriStandAdd-Ons/SLSC-EDS-Plugin-Custom-Device#2]
There is no initial indication that the EDS is loading the capability file from the card. Use the Set Busy/Unbusy to indicate to the person using the device that something is happening.

**Comment by Alexbarp** [comment]
Closing this Issue because this has been migrated to the new custom device repository. For future development, use [niveristand-slsc-eds-custom-device](https://github.com/ni/niveristand-slsc-eds-custom-device)
