### ISSUE TITLE
Import/Export Capability Needed

### ISSUE THREAD

**Issue by Sarci1** [NIVeriStandAdd-Ons/SLSC-EDS-Plugin-Custom-Device#4]
It would be ideal to have import/export capability for the individual custom device. This will allow me to export/import common configurations of modules and minimize channel bloat.

**Comment by Alexbarp** [comment]
Closing this Issue because this has been migrated to the new custom device repository. For future development, use [niveristand-slsc-eds-custom-device](https://github.com/ni/niveristand-slsc-eds-custom-device)
