### ISSUE TITLE
Multi-Property Value Application

### ISSUE THREAD

**Issue by Sarci1** [NIVeriStandAdd-Ons/SLSC-EDS-Plugin-Custom-Device#5]
I'd love to see the ability to change properties that share the same datatype simultaneously, i.e. select all the relevant switches using Shift and set the value appropriately to be reflected across all of them.

**Comment by Alexbarp** [comment]
Closing this Issue because this has been migrated to the new custom device repository. For future development, use [niveristand-slsc-eds-custom-device](https://github.com/ni/niveristand-slsc-eds-custom-device)
