### ISSUE TITLE
Provide hierarchy mask

### ISSUE THREAD

**Issue by Sarci1** [NIVeriStandAdd-Ons/SLSC-EDS-Plugin-Custom-Device#7]
It would be nice to allow the user of the EDS to define the hierarchy for the channels that will display in the VS tree.

**Comment by Alexbarp** [comment]
Closing this Issue because this has been migrated to the new custom device repository. For future development, use [niveristand-slsc-eds-custom-device](https://github.com/ni/niveristand-slsc-eds-custom-device)
